### ISSUE TITLE
html tags keyword arguments without quotes

### ISSUE THREAD

**Issue by enzolouis** [readthedocs-fr/bin-archive#1]
In bin.html, some tags don't have quotes in their keyword arguments. Like type, id, method, charset arguments ; example :
```html
<meta charset=utf-8>
<form method=POST>
<textarea name=code id=code
<input type=submit id=submit>
```
even though html is not sensitive, charset by example stay sensitive, code have to be converted to :
```html
<meta charset="utf-8">
<form method="POST">
<textarea name="code" id="code">
<input type="submit" id="submit">
```

**Comment by Julien00859** [comment]
From the html specification they are called *Unquoted attribute value syntax* which is a valid (yet uncommon) way to write attributes. See https://html.spec.whatwg.org/multipage/syntax.html#attributes-2 . Are you sure about the charset ?

You made me validate the html via the standard https://validator.w3.org/ validator. Every thing seems to be ok except for the `<a><button></button></a>`.

**Comment by AntoineJT** [comment]
I don't think the problem is the HTML charset, but more the storage encoding.
As you can see with the image below it has encoding problems
![image](https://user-images.githubusercontent.com/26577763/97123109-5cec7e00-172a-11eb-9d16-a5becf1f8252.png)

**Comment by Julien00859** [comment]
That's sure is a problem! @AntoineJT Could you open a new issue and provide original content + the html output when it is saved ?

**Comment by enzolouis** [comment]
My bad i thought the quotes "absence" in `<meta charset=utf-8>` provides the encoding error. But no with the @Julien00859 answer <a href="https://github.com/readthedocs-fr/bin/issues/1#issuecomment-716238499">here</a>

**Comment by AntoineJT** [comment]
@Julien00859 Yes, I've done that in #3
And I'm 100% sure the problem does not comes from the HTML meta charset

**Comment by Julien00859** [comment]
Thank you for the issue, I'll investigate it tomorrow. @EmberOn as the situation have been clarified not to be the quotes, may I close this issue ?

**Comment by enzolouis** [comment]
Yes you can 👍🏼
