### ISSUE TITLE
We can't scroll in paste viewer if we write a long text

### ISSUE THREAD

**Issue by enzolouis** [readthedocs-fr/bin-archive#4]
If we write a long text on the `/` route, where the main `<textarea>` is, there is no problem, the scrollbar is here : 
![scrollbar_bug](https://user-images.githubusercontent.com/65914622/97162337-5dfbca80-177f-11eb-8a3e-c60e22bd0edd.PNG)

but when we eventually click on `submit`, we are redirected to the paste we wrote, but the **text is cut** at the bottom of the page **without scrollbar**, __we can't scroll the paste__ : 
![scrollbar_bug2](https://user-images.githubusercontent.com/65914622/97162681-d3679b00-177f-11eb-9cec-ad9c5ba3f0ed.PNG)

**Comment by Julien00859** [comment]
@TNtube it sures is a problem of css, what do you think we split the template in two? I kinda thought it would be a good idea to have a single html file and to use the templating engine of bottle to "select" to show the new bin form or the show one existing bin. I think spliting the html/css/js in distinct files would be better.

**Comment by Julien00859** [comment]
Yup, css error there

https://github.com/readthedocs-fr/bin/blob/a310e591a34925acf6328b0325678715f418eb52/assets/bin.css#L12
